package jlecaro;

import db.Data;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Estudiante;
import model.TMModel;

public class Main extends javax.swing.JFrame {

    private Data data;
    private TMModel tmmodel;

    public Main() {
        initComponents();
        // Instrucción para brindar título a la ventana
        this.setTitle("Administrador de Asistencia Estudiantil");
        try {
            data = new Data("poo_evaluacion_3");
        } catch (SQLException ex) {
            System.out.println("[*] Error en la conexion a base de datos" + ex.getMessage());
        }
        //actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_General = new javax.swing.JPanel();
        panel_Superior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_Cuerpo = new javax.swing.JPanel();
        panel_Formulario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_rut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFormated_fecha = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_limpiar_campos = new javax.swing.JButton();
        cbo_sala = new javax.swing.JComboBox<>();
        btn_guardar_asistencia1 = new javax.swing.JButton();
        btn_actualizar_asistencia1 = new javax.swing.JButton();
        panel_filtros = new javax.swing.JPanel();
        btn_filtros = new javax.swing.JTextField();
        btn_filtros_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TM_Main_Model = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Superior.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("ADMINISTRADOR DE ASISTENCIA");

        javax.swing.GroupLayout panel_SuperiorLayout = new javax.swing.GroupLayout(panel_Superior);
        panel_Superior.setLayout(panel_SuperiorLayout);
        panel_SuperiorLayout.setHorizontalGroup(
            panel_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_SuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
        panel_SuperiorLayout.setVerticalGroup(
            panel_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SuperiorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panel_Cuerpo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        panel_Formulario.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulario de Asistencia"));
        panel_Formulario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel2.setText("RUT:");

        txt_rut.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("FECHA:");

        txtFormated_fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y-MM-dd"))));
        txtFormated_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFormated_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFormated_fechaActionPerformed(evt);
            }
        });

        jLabel4.setText("SALA:");

        btn_limpiar_campos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_limpiar_campos.setText("LIMPIAR");
        btn_limpiar_campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar_camposActionPerformed(evt);
            }
        });

        cbo_sala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_sala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_salaActionPerformed(evt);
            }
        });

        btn_guardar_asistencia1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_guardar_asistencia1.setText("GUARDAR");
        btn_guardar_asistencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_asistencia1ActionPerformed(evt);
            }
        });

        btn_actualizar_asistencia1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_actualizar_asistencia1.setText("ACTUALIZAR");
        btn_actualizar_asistencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_asistencia1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_FormularioLayout = new javax.swing.GroupLayout(panel_Formulario);
        panel_Formulario.setLayout(panel_FormularioLayout);
        panel_FormularioLayout.setHorizontalGroup(
            panel_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FormularioLayout.createSequentialGroup()
                .addGroup(panel_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_FormularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_sala, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_rut)
                            .addComponent(txtFormated_fecha)))
                    .addGroup(panel_FormularioLayout.createSequentialGroup()
                        .addGroup(panel_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_FormularioLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2))
                            .addGroup(panel_FormularioLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel4))
                            .addGroup(panel_FormularioLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel3))
                            .addGroup(panel_FormularioLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btn_guardar_asistencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_FormularioLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btn_limpiar_campos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_FormularioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_actualizar_asistencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        panel_FormularioLayout.setVerticalGroup(
            panel_FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FormularioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFormated_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cbo_sala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btn_guardar_asistencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_actualizar_asistencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_limpiar_campos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panel_filtros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        btn_filtros_buscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_filtros_buscar.setText("BUSCAR");
        btn_filtros_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtros_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_filtrosLayout = new javax.swing.GroupLayout(panel_filtros);
        panel_filtros.setLayout(panel_filtrosLayout);
        panel_filtrosLayout.setHorizontalGroup(
            panel_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_filtrosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_filtros)
                .addGap(18, 18, 18)
                .addComponent(btn_filtros_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        panel_filtrosLayout.setVerticalGroup(
            panel_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_filtrosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_filtros_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        TM_Main_Model.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TM_Main_Model);

        javax.swing.GroupLayout panel_CuerpoLayout = new javax.swing.GroupLayout(panel_Cuerpo);
        panel_Cuerpo.setLayout(panel_CuerpoLayout);
        panel_CuerpoLayout.setHorizontalGroup(
            panel_CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Formulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_filtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_CuerpoLayout.setVerticalGroup(
            panel_CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_CuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_Formulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_CuerpoLayout.createSequentialGroup()
                        .addComponent(panel_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_GeneralLayout = new javax.swing.GroupLayout(panel_General);
        panel_General.setLayout(panel_GeneralLayout);
        panel_GeneralLayout.setHorizontalGroup(
            panel_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_GeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_Cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_GeneralLayout.setVerticalGroup(
            panel_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_GeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_Cuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_salaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_salaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_salaActionPerformed

    private void btn_filtros_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtros_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_filtros_buscarActionPerformed

    private void btn_limpiar_camposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar_camposActionPerformed
        
    }//GEN-LAST:event_btn_limpiar_camposActionPerformed

    private void btn_guardar_asistencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_asistencia1ActionPerformed
        try {
            Estudiante estudiante = new Estudiante();
            String rut = txt_rut.getText();
            String fechaAsistencia = txtFormated_fecha.getText();
            String sala = cbo_sala.getItemAt(WIDTH);

            estudiante.setRut(rut);
            estudiante.setFechaAsistencia(fechaAsistencia);
            //estudiante.setFechaPublicacion(LocalDate.parse(fechaPublicacion));
            estudiante.setSala(sala);

            data.agregarEstudiante(estudiante);
            JOptionPane.showMessageDialog(this, "Estudiante agregado con éxito!!");
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_guardar_asistencia1ActionPerformed

    private void txtFormated_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFormated_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormated_fechaActionPerformed

    private void btn_actualizar_asistencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_asistencia1ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btn_actualizar_asistencia1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TM_Main_Model;
    private javax.swing.JButton btn_actualizar_asistencia1;
    private javax.swing.JTextField btn_filtros;
    private javax.swing.JButton btn_filtros_buscar;
    private javax.swing.JButton btn_guardar_asistencia1;
    private javax.swing.JButton btn_limpiar_campos;
    private javax.swing.JComboBox<String> cbo_sala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_Cuerpo;
    private javax.swing.JPanel panel_Formulario;
    private javax.swing.JPanel panel_General;
    private javax.swing.JPanel panel_Superior;
    private javax.swing.JPanel panel_filtros;
    private javax.swing.JFormattedTextField txtFormated_fecha;
    private javax.swing.JTextField txt_rut;
    // End of variables declaration//GEN-END:variables


    public void actualizarTabla(){
    
    try{
        tmmodel = new TMModel(data.obtenerListaDeEstudiantes());
        TM_Main_Model.setModel(tmmodel);
    
    } catch(SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    public void limpiarCampos() {
        txt_rut.setText("");
        txtFormated_fecha.setText("");
    }


}
